package:
  name: platformio-tool-teensy
  version: 1.21.0

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0
  script: pio platform install teensy --skip-default-package --with-package=tool-teensy

requirements:
  build:
    - platformio-platform-teensy

  run:
    - platformio-platform-teensy
