package:
  name: platformio-tool-teensy
  version: 1.21.0

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - pywget
    # Include `git`, since it includes `tar`
    - git # [win]
    - platformio-platform-teensy

  run:
    - platformio-platform-teensy
